#! /bin/sh
xsetroot -cursor_name left_ptr &
setxkbmap tr &
picom --vsync &
nitrogen --restore &
wal -r &
wal -R &
sh startpipewire.sh &
polybar DTX & 
sxhkd &
udiskie & 
 
bspc config split_ratio		0.60
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod1
 
bspc config automatic_scheme	spiral
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc config border_width 0
bspc config border_gap 8
